# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 194988ae51048d1efca17935372ac22ddb1fe73deab7613791393d84af603555d7e476105b9e3470b05b4f04f1ac1a70137147c83652b66a26fb67709b43dac1

test:
  secret_key_base: f6f692b7f890701c359e93031b13165cbbe02d622119ce2d31064f4c25133b57d1a49e17f1e3225f76dc71645ac0bfc6758a766c0db2fb7327348045fa34cd41

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
